  select
  exchange_type             ,
  stock_code                ,
  stock_type                ,
  internal_code             ,
  frozen_code               ,
  money_type                ,
  stock_name                ,
  spell_code                ,
  relative_code             ,
  stkcode_status            ,
  bond_term                 ,
  default_price             ,
  base_price                ,
  last_price                ,
  close_price               ,
  net_value                 ,
  up_price                  ,
  down_price                ,
  high_amount               ,
  low_amount                ,
  trustee                   ,
  overdraw                  ,
  asset_flag                ,
  amount_per_hand           ,
  store_unit                ,
  report_unit               ,
  buy_unit                  ,
  sell_unit                 ,
  price_step                ,
  price_grade               ,
  report_direction          ,
  fund_direction            ,
  stock_direction           ,
  fund_frozen               ,
  fund_real_back            ,
  stock_real_back           ,
  match_type                ,
  tn_type                   ,
  fund_back_n               ,
  stock_back_n              ,
  par_value                 ,
  hold_amount               ,
  market_date               ,
  defaultprice_type         ,
  limitprice_type           ,
  baseprice_type            ,
  limit_value_up            ,
  limit_value_low           ,
  buy_client                ,
  sell_client               ,
  buy_holder                ,
  sell_holder               ,
  en_entrust_way            ,
  elig_risk_level           ,
  low_balance               ,
  high_balance              ,
  cancel_low_balance        ,
  cancel_high_balance       ,
  issue_date                ,
  modify_date               ,
  bondinv_flag              ,
  delist_flag               ,
  delist_date              ,
  stbtrans_type             ,
  sub_stock_type            ,
  stbtrans_status           ,
  stkcode_ctrlstr           ,
  exdividend_flag           ,
  marketmaker_amount        ,
  trans_price               ,
  market_high_amount        ,
  market_low_amount         ,
  stock_name_long           ,
  market_buy_unit           ,
  market_sell_unit          ,
  bond_end_date             ,
  put_price                 ,
  a.rowid
  from hs_user.stkcode a
  where length(a.stock_code) = 6
 -- and a.exchange_type = '2'
  --and a.stock_type = '0'
  and a.stock_code like '1224%'
  

